"""extend assets table

Revision ID: 0305134a1fb8
Revises: e0c34b01088a
Create Date: 2026-07-29 09:38:54.006010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0305134a1fb8'
down_revision: Union[str, Sequence[str], None] = 'e0c34b01088a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "assets",
        sa.Column(
            "asset_type",
            sa.String(length=50),
            nullable=False,
            server_default="server",
        ),
    )

    op.add_column(
        "assets",
        sa.Column(
            "criticality",
            sa.String(length=20),
            nullable=False,
            server_default="medium",
        ),
    )

    op.add_column(
        "assets",
        sa.Column(
            "environment",
            sa.String(length=50),
            nullable=False,
            server_default="production",
        ),
    )

    op.add_column(
        "assets",
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="online",
        ),
    )

    op.add_column(
        "assets",
        sa.Column(
            "last_seen",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('assets', 'last_seen')
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'environment')
    op.drop_column('assets', 'criticality')
    op.drop_column('assets', 'asset_type')
    # ### end Alembic commands ###

