"""add timestamps to existing models

Revision ID: f272db41c95d
Revises: 36ef7600af2b
Create Date: 2026-07-24 10:11:11.055546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f272db41c95d'
down_revision: Union[str, Sequence[str], None] = '36ef7600af2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('threats', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('threats', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('vulnerabilities', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('vulnerabilities', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'updated_at')
    op.drop_column('vulnerabilities', 'created_at')
    op.drop_column('threats', 'updated_at')
    op.drop_column('threats', 'created_at')
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    # ### end Alembic commands ###
